name: verify

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Update gh-pages branch
      run: |
        git fetch origin gh-pages:gh-pages
        git checkout gh-pages
        git merge origin/master -m "Merge master to update gh-pages"
        git push origin gh-pages
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all
